# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Build package"

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    permissions:
      contents: read
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: "🐍 Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "⚙️ Install Poetry"
        uses: "abatilo/actions-poetry@v4.0.0"
        # Automatic installation of plugins fails due to https://github.com/python-poetry/poetry/issues/10028
        # so we still do a `self add`
      - name: "⚙️ Install dependencies"
        run: |
          poetry install --without dev
          poetry self add "poetry-dynamic-versioning[plugin]"
      - name: "🚀 Test package building"
        run: "poetry build"
