name: Pytoyoda documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@v5
      - name: "🐍 Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: "⚙️ Install Poetry"
        uses: "abatilo/actions-poetry@v4.0.0"
      - name: "⚙️ Install dependencies"
        run: poetry install
      - name: "🚀 Generate docs"
        run: poetry run pdoc pytoyoda -o docs/ --docformat google
      - name: "⬆️ Upload docs artifact"
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
