name: "Test code"

env:
  COLUMNS: 120

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  pytest:
    name: "Pytest"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    env:
      OS: "ubuntu-latest"
      PYTHON: "${{ matrix.python-version }}"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: "🐍 Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "⚙️ Install Poetry"
        uses: "abatilo/actions-poetry@v4.0.0"
      - name: "⚙️ Install dependencies"
        run: "poetry install"
      - name: "🚀 Run pytest with coverage"
        run: |
          poetry run pytest --cov=pytoyoda --cov-report term --cov-report xml:coverage.xml
      - name: "⬆️ Archive code coverage results"
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-python${{ matrix.python-version }}
          path: coverage.xml
          retention-days: 1
  codacy:
    if: github.repository_owner == 'pytoyoda'
    name: "Codacy coverage reporter"
    needs: pytest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: "⤵️ Download test coverage artifact"
        uses: actions/download-artifact@v4
        with:
          name: test-coverage-python3.10
      - name: "🚀 Run codacy-coverage-reporter"
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.xml
